# ******************* Install "REST Client" extension on VS Code ***************************
# ********* Click on "Send Request" link above each request to execute it ******************

GET http://localhost:5000/

# ************************************* Auth ***********************************************

### Signup
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "fullname": "John Doe",
  "email": "john.doo@example.com",
  "password": "password"
}

### Login 
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

### Logout 
POST http://localhost:5000/api/auth/logout
Content-Type: application/json

### Get user Details
GET  http://localhost:5000/api/auth/checkAuth

### post request for updating profile picture
POST http://localhost:5000/api/auth/changeProfilePic
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123",
  "profilePic": "../frontend/public/avatar.png"
}

# ************************************* Messages *******************************************

### Get users for sidebar
GET http://localhost:5000/api/messages/users
Authorization: Bearer <your_token_here>

### Get messages for a specific user
GET http://localhost:5000/api/messages/67be0111c80553c8e384062e
Authorization: Bearer <your_token_here>

### Send a message to a specific user
POST http://localhost:5000/api/messages/send/67be0111c80553c8e384062e
Authorization: Bearer <your_token_here>
Content-Type: application/json

{
  "text": "Hello, this is a test message!",
  "image": ""
}